name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install & Test:Cov & Upload:Cov
        run: yarn install && yarn test --coverage && yarn codecov -t $TOKEN
        with:
          TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build docs
        run: yarn doc:build

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1 # This step installs the ssh client into the workflow run. There's many options available for this on the action marketplace.
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy Github Page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: docs/dist
          SSH: true
